"""Added initial tables

Revision ID: 1bb1767af4ef
Revises: 421cf0da30f6
Create Date: 2022-05-23 16:46:09.604118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb1767af4ef'
down_revision = '421cf0da30f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
